# fly.toml app configuration file generated for tablerise-bot on 2023-07-01T21:14:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tablerise-bot"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1